name: dotnet
on: push
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2.1.0
    - run: |
        dotnet pack \
        -c Release \
        -o dist \
        --include-source \
        --include-symbols \
        -p:PackageVersion=1.0.${{github.run_number}} \
        -p:RepositoryUrl=${{github.repositoryUrl}}
    - run: |
        dotnet nuget push \
        dist/**/*.symbols.nupkg \
        -k ${{github.token}} \
        -s https://nuget.pkg.github.com/oscarhult/index.json \
        --skip-duplicate
