name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0 
    - name: Pack
      run: dotnet pack -c Release -o dist -p:PackageVersion=1.0.${{github.run_number}} -p:RepositoryUrl=${{github.repositoryUrl}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: openssl-net
        path: dist/**/*.nupkg
    - name: Publish the package to GPR
      run: dotnet nuget push dist/**/*.nupkg -k ${{github.token}} -s https://nuget.pkg.github.com/oscarhult/index.json
